Check if user is admin when logging in
techswitch-learners/whale-spotting-2023-jan-backend pull request #25
Opened 2023-03-31 11:19 UTC by Verney2073

2023-04-02 18:15 UTC, francescastocco requested changes
If we use the existing `getUserById` endpoint then we don't need any backend changes for this :)

2023-04-03 09:53 UTC, keqichen commented on WhaleSpotting/Controllers/LoginController.cs
> +        return Unauthorized("User is not admin");
We will have the type error if we return a boolean here:
![image](https://user-images.githubusercontent.com/61296323/229475565-bea28712-4b11-4d47-aebd-f6dde8233a0b.png)
So we just changed this to one line by using ternary operator:
![image](https://user-images.githubusercontent.com/61296323/229475943-bc3b2e9e-82f6-4d6e-bfbe-74809d4dc018.png)

2023-04-03 10:27 UTC, francescastocco commented on WhaleSpotting/Controllers/LoginController.cs
> +        return Unauthorized("User is not admin");
We can change the return type of the controller method to return bool instead of IActionResult

2023-04-03 10:47 UTC, keqichen commented on WhaleSpotting/Controllers/LoginController.cs
> +        return Unauthorized("User is not admin");
It seems to be fine to keep it as IAcitonResult, please review our front-end changes, thank you :)

2023-04-03 11:07 UTC, francescastocco approved these changes

2023-04-03 14:08 UTC, merged