Fs create sighting
techswitch-learners/whale-spotting-2023-jan-backend pull request #29
Opened 2023-04-03 13:59 UTC by keqichen

2023-04-03 15:56 UTC, francescastocco requested changes
Looks good!

2023-04-03 15:56 UTC, francescastocco commented on WhaleSpotting/Services/WhaleSightingService.cs
> +
Extra line here

2023-04-03 15:56 UTC, francescastocco commented on WhaleSpotting/Services/WhaleSightingService.cs
> +        // User user = _users.GetById(6);
can we remove this comment?

2023-04-03 15:56 UTC, francescastocco commented on WhaleSpotting/Services/WhaleSightingService.cs
> +        var ourUser = _users.GetByUsername(userName);
Can we use the correct types here and rename the user variable?
```suggestion
        string userName = AuthHelper.ExtractFromAuthHeader(authHeader).Username;
        User user = _users.GetByUsername(userName);
```

2023-04-04 09:40 UTC, keqichen commented on WhaleSpotting/Models/Request/WhaleSightingRequest.cs
> +    public string? WhaleSpecies { get; set; }
We want to make PhotoImageURL and Description optional, but not sure about  WhaleSpecies. We could discuss it with the group.

2023-04-04 14:38 UTC, francescastocco approved these changes
Nice!

2023-04-05 11:42 UTC, merged